stages:
  # - code-quality-check
  - e2e
  - build
  - deploy

# es-lint:
#   stage: code-quality-check
#   image: node:22.1.0
#   script:
#     - npm install --only-dev --legacy-peer-deps
#     - npx eslint '**/*.js' --max-warnings=0
#   allow_failure: true

# sonarqube:
#   stage: code-quality-check
#   image: node:22.1.0
#   script:
#     - npm install --only-dev --legacy-peer-deps
#     - node sonar.js $SONAR_HOST_URL $SONAR_TOKEN
#   allow_failure: true

e2e:
  stage: e2e
  image: node:22.1.0
  variables:
    TEST_ENV: "dev"
    PLAYWRIGHT_BROWSERS_PATH: "playwright-browsers"
  cache:
    key: playwright-browsers
    paths:
      - playwright-browsers/
  script:
    - apt-get update && apt-get install -y libnspr4 libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxcomposite1 libxrandr2 libxdamage1 libxkbcommon0 libgbm1 libpango-1.0-0 libasound2 libXfixes3
    - npm ci --legacy-peer-deps
    - npx playwright install chromium
    - npx playwright test --project=chromium
  artifacts:
    when: always
    paths:
      - playwright-report/
      - test-results/
    reports:
      junit: test-results/junit.xml
  allow_failure: true
  only:
    - ua-module-01

build:
  stage: build
  image: docker:20.10.16
  services:
    - name: docker:20.10.16-dind
      alias: docker
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo $CI_REGISTRY
    - apk add --no-cache aws-cli
    - aws ecr describe-repositories --repository-names microservices/${CI_PROJECT_NAME} --region ap-southeast-1 || aws ecr create-repository --repository-name microservices/${CI_PROJECT_NAME} --region ap-southeast-1
    - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 096985928716.dkr.ecr.ap-southeast-1.amazonaws.com
    - docker build -t registry.dilligentech.com/dt/paas/nimbuz-portal-fe:dev --build-arg ENV=dev .
    - docker tag registry.dilligentech.com/dt/paas/${CI_PROJECT_NAME}:dev 096985928716.dkr.ecr.ap-southeast-1.amazonaws.com/microservices/${CI_PROJECT_NAME}:dev
    - docker push 096985928716.dkr.ecr.ap-southeast-1.amazonaws.com/microservices/${CI_PROJECT_NAME}:dev
  only:
    - dev

image-release:
  stage: build
  image: docker:20.10.16
  services:
    - name: docker:20.10.16-dind
      alias: docker
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo $CI_REGISTRY
    - apk add --no-cache aws-cli jq
    - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 096985928716.dkr.ecr.ap-southeast-1.amazonaws.com
    - docker build -t registry.dilligentech.com/dt/paas/nimbuz-portal-fe:$(jq .version package.json -r) --build-arg ENV=prod .
    - docker tag registry.dilligentech.com/dt/paas/${CI_PROJECT_NAME}:$(jq .version package.json -r) 096985928716.dkr.ecr.ap-southeast-1.amazonaws.com/microservices/${CI_PROJECT_NAME}:$(jq .version package.json -r)
    - docker push 096985928716.dkr.ecr.ap-southeast-1.amazonaws.com/microservices/${CI_PROJECT_NAME}:$(jq .version package.json -r)
  only:
    - master

deploy:
  stage: deploy
  image: ubuntu:latest
  script:
    - apt update -y && apt install wget curl -y
    - wget https://get.helm.sh/helm-v3.15.0-linux-amd64.tar.gz
    - tar -xvzf helm-v3.15.0-linux-amd64.tar.gz
    - mv linux-amd64/helm /usr/bin/
    - rm -rf linux-amd64
    - helm repo add --username $HELM_REGISTRY_USER --password $HELM_REGISTRY_TOKEN dt-charts ${CI_API_V4_URL}/projects/34/packages/helm/stable
    - helm upgrade --install portal dt-charts/microservice --set namespace=nimbuz-dev --set env=dev --set subDomain=app --set appName=portal --set image.repository=096985928716.dkr.ecr.ap-southeast-1.amazonaws.com/microservices/nimbuz-portal-fe --set image.tag=dev --set image.pullPolicy=Always --set service.targetPort=80 --namespace nimbuz-dev
  only:
    - dev

deploy-prod:
  stage: deploy
  image: ubuntu:latest
  # when: manual
  script:
    - apt update -y && apt install jq wget curl -y
    - wget https://get.helm.sh/helm-v3.15.0-linux-amd64.tar.gz
    - tar -xvzf helm-v3.15.0-linux-amd64.tar.gz
    - mv linux-amd64/helm /usr/bin/
    - rm -rf linux-amd64
    - helm repo add --username $HELM_REGISTRY_USER --password $HELM_REGISTRY_TOKEN dt-charts ${CI_API_V4_URL}/projects/34/packages/helm/stable
    - helm upgrade --install portal dt-charts/microservice --set namespace=nimbuz-prod --set env=prod --set subDomain=app --set appName=portal --set image.repository=096985928716.dkr.ecr.ap-southeast-1.amazonaws.com/microservices/${CI_PROJECT_NAME} --set image.tag=$(jq .version package.json -r) --set image.pullPolicy=Always --set service.targetPort=80 --namespace nimbuz-prod
  only:
    - master
