import { test, expect } from '@playwright/test';

test.beforeEach(async ({ page }) => {
 
  await page.addInitScript(() => {
    try {
      localStorage.setItem('accessToken', 'eyJhbGciOiJSUzI1NiIsImtpZCI6Im5pbWJ1ei1jZXJ0IiwidHlwIjoiSldUIn0.eyJvd25lciI6Im5pbWJ1eiIsIm5hbWUiOiJEZXYiLCJjcmVhdGVkVGltZSI6IjIwMjUtMTItMzBUMTM6MDI6MjZaIiwidXBkYXRlZFRpbWUiOiIyMDI1LTEyLTMwVDEzOjA1OjQwWiIsImRlbGV0ZWRUaW1lIjoiIiwiaWQiOiJiODQ0ZmNkYS05ZWJkLTQwOTUtYmYxYy0yZWUwYThiNDA2YTAiLCJ0eXBlIjoiIiwicGFzc3dvcmQiOiIiLCJwYXNzd29yZFNhbHQiOiIiLCJwYXNzd29yZFR5cGUiOiJwbGFpbiIsImRpc3BsYXlOYW1lIjoiRGV2IiwiZmlyc3ROYW1lIjoiIiwibGFzdE5hbWUiOiIiLCJhdmF0YXIiOiIiLCJhdmF0YXJUeXBlIjoiIiwicGVybWFuZW50QXZhdGFyIjoiIiwiZW1haWwiOiJtYW5vcmFuaml0aC5wZEBnbWFpbC5jb20iLCJlbWFpbFZlcmlmaWVkIjpmYWxzZSwicGhvbmUiOiIiLCJjb3VudHJ5Q29kZSI6IiIsInJlZ2lvbiI6IiIsImxvY2F0aW9uIjoiIiwiYWRkcmVzcyI6W10sImFmZmlsaWF0aW9uIjoiIiwidGl0bGUiOiIiLCJpZENhcmRUeXBlIjoiIiwiaWRDYXJkIjoiIiwiaG9tZXBhZ2UiOiIiLCJiaW8iOiIiLCJsYW5ndWFnZSI6IiIsImdlbmRlciI6IiIsImJpcnRoZGF5IjoiIiwiZWR1Y2F0aW9uIjoiIiwic2NvcmUiOjAsImthcm1hIjowLCJyYW5raW5nIjo1LCJpc0RlZmF1bHRBdmF0YXIiOmZhbHNlLCJpc09ubGluZSI6ZmFsc2UsImlzQWRtaW4iOmZhbHNlLCJpc0ZvcmJpZGRlbiI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsInNpZ251cEFwcGxpY2F0aW9uIjoibmltYnV6IiwiaGFzaCI6IiIsInByZUhhc2giOiIiLCJhY2Nlc3NLZXkiOiIiLCJhY2Nlc3NTZWNyZXQiOiIiLCJnaXRodWIiOiIiLCJnb29nbGUiOiIiLCJxcSI6IiIsIndlY2hhdCI6IiIsImZhY2Vib29rIjoiIiwiZGluZ3RhbGsiOiIiLCJ3ZWlibyI6IiIsImdpdGVlIjoiIiwibGlua2VkaW4iOiIiLCJ3ZWNvbSI6IiIsImxhcmsiOiIiLCJnaXRsYWIiOiIiLCJjcmVhdGVkSXAiOiIiLCJsYXN0U2lnbmluVGltZSI6IiIsImxhc3RTaWduaW5JcCI6IiIsInByZWZlcnJlZE1mYVR5cGUiOiIiLCJyZWNvdmVyeUNvZGVzIjpudWxsLCJ0b3RwU2VjcmV0IjoiIiwibWZhUGhvbmVFbmFibGVkIjpmYWxzZSwibWZhRW1haWxFbmFibGVkIjpmYWxzZSwibGRhcCI6IiIsInByb3BlcnRpZXMiOnsiYnVzaW5lc3NOYW1lIjoibmltYnV6IiwiaXNWZXJpZmllZCI6InRydWUiLCJuaW1idXpBY2NvdW50SWQiOiJiNjliZjczYi05ZGIwLTQ1M2QtOTZlNS00MzMwYmY2YjNkYzYiLCJuaW1idXpVc2VySWQiOiI5OTg0ZDE3Zi0yNDllLTRkZjMtYTMxZC0wOWEyMzc4YTFlZDQiLCJ0eXBlIjoiaW5kaXZpZHVhbCJ9LCJyb2xlcyI6W10sInBlcm1pc3Npb25zIjpbXSwiZ3JvdXBzIjpbXSwibGFzdFNpZ25pbldyb25nVGltZSI6IiIsInNpZ25pbldyb25nVGltZXMiOjAsIm1hbmFnZWRBY2NvdW50cyI6bnVsbCwidG9rZW5UeXBlIjoiYWNjZXNzLXRva2VuIiwidGFnIjoiIiwiYXpwIjoibmltYnV6IiwiaXNzIjoiaHR0cHM6Ly9jYXNkb29yLmRldi5uaW1idXoudGVjaCIsInN1YiI6ImI4NDRmY2RhLTllYmQtNDA5NS1iZjFjLTJlZTBhOGI0MDZhMCIsImF1ZCI6WyJuaW1idXoiXSwiZXhwIjoxNzcxMjQzNDcwLCJuYmYiOjE3NzA2Mzg2NzAsImlhdCI6MTc3MDYzODY3MCwianRpIjoiYWRtaW4vMWVmYWJiMjUtOGZmMi00MjhiLWFmNGEtN2UwMWRjZjI4Njg2In0.eq6vS6zRLnNVrG_gzaUTbXlVW1XltwISNnAycwe7ysHRT47KIfVMo7rxHgik44Sp-WiEd_8Sq96KA3NlkVZEbeOqXOEF203Vc25McmGCHJsed8-hm51PK3hJNZJaiQLrV3Y5jprivQcyTWnuN7DtHo0b6cYnErZtstYpwjNu70-AZNv5SiYl2ObgiSihddaoaBl-IVAlX5_RzP8HPqmD3PwHTaDtd8auG01-mkL0fWuIDa24Mads_yvkSvCkLwI7wnovyo09Tcu8njzsH4avGRV73r9akN8xQ0HJ3YuaIvWdOSfvoFMM-KcZiUJMlbfXEAQL6PG2IkkUmCR7WkCP7hFFNEbroNy6FhdyrLoRP0xsWILTDWv6WrJlnyOTA-of-M1GQYOtKcBHjMRbWJ6MWBSYMiMZ_e-wg4oRZUTwgFXCrHUL963kFxDNtyQ_mxayZ43Jmue7McCVp7bZhnV-MEMyQMVAOIqp_9mTpoLCKM5rjYxrHtRiRPoc5vDIxODiu3LG_eB6ItDXPraz5tATe_3BRqNHvu8R7ev4MrPvAD-XFLrCVR_gtzgPe3H4Q0FitEeP75fFk-KAnKD8d8q9gU_nlmx1_HLw-3bTbgTN9W6HTznj34B23XRsN6kj06f1h1cPuo5zNtn6VXKDwCTsHH9TyazhO_H-hmLF_5q5J8I');
      localStorage.setItem('userId', 'test-user');
      localStorage.setItem('accountId', 'test-account');
      const policies = [{ V0: 'test-user', V4: 'ADMIN' }];
      localStorage.setItem('policies', JSON.stringify(policies));
    } catch (e) {
      // ignore
    }
  });


  
  
});
